out_dir: "/home/ac715y/snakemake_results"
background: "/home/ac715y/Searchlight2/backgrounds/human_GRCh38.p13.tsv"
sample_sheet: "/home/ac715y/scripts/tsv_output/sample_sheet.tsv"
ora_file: "/home/ac715y/scripts/tsv_output/GO_human_BP.tsv"
data_dir: "/home/ac715y/scripts/tsv_output"

subtypes:
  - Intestinal_Epithelial
  - Epithelial
  - Epithelial_Inflam
  - Endothelial
  - B
  - Plasma_B
  - Immune_T_NK
  - Macrophage_Dendritic_Monocytes
  - Mast
  - Myo_Fibro_stromal
  - Neuron_Glial
  - Smooth_Muscle_Fibroblasts
  - All

de_subtypes:
  - int_epithelial
  - epithelial
  - epithelial_inflam
  - endo
  - B
  - plasma_b
  - Immune_T_NK
  - macro_mono_den
  - mast
  - myo_fibro_stromal
  - neuron_glial
  - smooth_muscle_fibroblasts
  - all
